### ISSUE TITLE
TypeError: Cannot read property 'getParent' of undefined

### ISSUE THREAD

**Issue by saresh-krish** [react-component/util#116]
Hi 
I got this error in when i click the Modal popup event .
I thick this problem come from the latest package of 'rc-util'.
`if (!windowIsUndefined && this.getParent() === document.body) {
        // 离开时不会 render， 导到离开时数值不变，改用 func 。。
        openCount = visible && openCount ? openCount - 1 : openCount;
      }`
path: node_modules/rc-util/es/PortalWrapper.js

how you fixed this?
i got the same issue on Liver server and local.
any idea to fix this problem.
### Environment
"antd": "^4.1.2",
"react": "^16.13.1",
System -  Ubuntu 18.04.3 LTS
Browser - Version 79.0.3945.130 (Official Build) (64-bit)

**Comment by chenhebing** [comment]
https://github.com/react-component/util/blob/master/src/PortalWrapper.js#L54

静态方法里面拿不到实例方法的吧，这个没有经过测试的吗。。。

**Comment by jljsj33** [comment]
https://github.com/react-component/util/commit/b64a03b89ac35a8f7590d4bd183e24b4042d252a
