### ISSUE TITLE
hi~

### ISSUE THREAD

**Issue by remotesc2** [react-component/util#12]
I have a question...
What is es?

**Comment by FourKnife** [comment]
Maybe he means "where is es?"

**Comment by remotesc2** [comment]
I know where is es, but i dont real mean what is es, ECMAScript?

**Comment by FourKnife** [comment]
Yep

2017-06-01 20:23 GMT+08:00 remotesc2 <notifications@github.com>:

**Comment by paranoidjk** [comment]
https://github.com/ant-design/antd-tools/issues/39
