### ISSUE TITLE
package.json 缺失 peerDependencies 字段

### ISSUE THREAD

**Issue by Zousdie** [react-component/util#140]
Skypack 是一个分发 ESM 模块的 CDN，我正在通过 Skypack 使用 react 和 antd 开发应用程序，但在加载 antd 模块的过程中出现了错误。

由于 rc-util 的代码中依赖了 react-dom 而没有在 package.json 中通过 peerDependencies 字段声明，Skypack 无法判断出此时如何加载 react-dom.

希望维护者可以补全 peerDependencies 字段，修复这个问题。

#138

**Comment by yoyo837** [comment]
Close by #163
