### ISSUE TITLE
Warning: React does not recognize the `scrollLocker`

### ISSUE THREAD

**Issue by srw4115** [react-component/util#183]
Warning: React does not recognize the `scrollLocker` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `scrolllocker` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

at PortalWrapper

**Comment by shaodahong** [comment]
Use `Drawer` componentt? if use PortalWrapper you need omit `scrollLocker`

**Comment by srw4115** [comment]
> Use `Drawer` componentt? if use PortalWrapper you need omit `scrollLocker`

yes, in **Drawer**, this error happend when i use **umijs and chose antd-pro** in new project, **here is the more info about error:**



Warning: React does not recognize the `scrollLocker` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `scrolllocker` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at div
    at DrawerChild (http://localhost:8000/umi.js:119877:94)
    at http://localhost:8000/umi.js:137343:25
    at PortalWrapper (http://localhost:8000/umi.js:137563:5)
    at DrawerWrapper (http://localhost:8000/umi.js:120512:94)
    at Drawer (http://localhost:8000/umi.js:70620:81)
    at DrawerWrapper (http://localhost:8000/umi.js:70908:34)
    at SiderMenuWrapper (http://localhost:8000/umi.js:51939:24)
    at section
    at BasicLayout (http://localhost:8000/umi.js:73638:76)
    at Layout (http://localhost:8000/umi.js:73606:79)
    at div
    at Provider (http://localhost:8000/umi.js:185353:31)
    at BasicLayout (http://localhost:8000/umi.js:48098:24)
    at BasicLayout (http://localhost:8000/layouts__BasicLayout.js:1117:24)
    at Connect(BasicLayout) (http://localhost:8000/umi.js:169187:75)
    at LoadableComponent (http://localhost:8000/umi.js:63233:75)
    at Route
    at Switch
    at SecurityLayout

**Comment by Clago** [comment]
一样的问题，不知道改了啥。

**Comment by tobiasriemenschneider** [comment]
Hi!
Using `"antd": "^4.10.0"` I'm also getting this error.
Am I doing something wrong or do I need to wait for it to be fixed?
Thanks for any help. 🙏

<img width="1094" alt="Bildschirmfoto 2021-01-08 um 07 04 21" src="https://user-images.githubusercontent.com/3159548/103980225-c43d9a00-517f-11eb-832a-d8728de8f193.png">

**Comment by shaodahong** [comment]
Waiting antd `4.10.1` release.

**Comment by RabbDream** [comment]
same error,use Tree component in Drawer component

**Comment by shaodahong** [comment]
> same error,use Tree component in Drawer component

version?

**Comment by RabbDream** [comment]
> > same error,use Tree component in Drawer component
> 
> version?

4.10.0

**Comment by Clago** [comment]
> > same error,use Tree component in Drawer component
> 
> version?

4.10.1 scrollLocker 修复了。但是 switchScrollingEffect 这个错误出现了。

**Comment by RabbDream** [comment]
> > > same error,use Tree component in Drawer component
> > 
> > 
> > version?
> 
> 4.10.1 scrollLocker 修复了。但是 switchScrollingEffect 这个错误出现了。

悄无声息的周末加班发了个版本,我都没注意,我去更新一下

**Comment by KrishnaPG** [comment]
Encountering same error with `4.10.0` of antd

![image](https://user-images.githubusercontent.com/4610831/104411892-40294f00-5591-11eb-967c-d8778fa12681.png)

**Comment by shaodahong** [comment]
> Encountering same error with `4.10.0` of antd
> 

You need upgrade `antd` to latest version

**Comment by tobiasriemenschneider** [comment]
Yes, updating to the latest version (`4.10.2`) fixed it for me. 👍
Thank You!!
