### ISSUE TITLE
Can't resolve 'rc-util/es/Children/toArray'

### ISSUE THREAD

**Issue by thamys** [react-component/util#192]
I just initiate a project with next and Ant Design and I have this error:

![image](https://user-images.githubusercontent.com/2211332/103959900-b4966500-512f-11eb-9a89-c754c77c0062.png)

**Comment by robert-wettstaedt** [comment]
I have a similar error:

```
Failed to compile.

./node_modules/rc-input-number/es/StepHandler.js
Module not found: Can't resolve 'rc-util/es/isMobile'
```

Versions:

antd@4.13.0
rc-input-number@7.0.0
rc-util@5.8.1
