### ISSUE TITLE
rc-util warning  

### ISSUE THREAD

**Issue by kaoding** [react-component/util#298]
WARNING  Compiled with 1 warnings                                                                                                                                                    10:12:06

 warning  in ./node_modules/rc-util/es/React/render.js

export 'createRoot' (imported as 'ReactDOM') was not found in 'react-dom' (possible exports: __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED, createPortal, findDOMNode, flushSync, hydrate, render, unmountComponentAtNode, unstable_batchedUpdates, unstable_createPortal, unstable_renderSubtreeIntoContainer, version)

**Comment by kaoding** [comment]
![image](https://user-images.githubusercontent.com/18542211/164358236-e8f3ec0a-cef1-4e15-9b8f-8b325871bb42.png)

**Comment by zombieJ** [comment]
@kaoding 给个重现看一下？

**Comment by kaoding** [comment]
antd pro 默认 yarn start 就能看到，但将 react 升级到 18 后消失了，就是有这个提示也没有发现不能使用的问题，所以就关了这个。
