### ISSUE TITLE
vite/rc-util@5.37.0: error message occurred does not provide an export named 'isFragment'

### ISSUE THREAD

**Issue by conero** [react-component/util#461]
vite@4.4.9: `rc-util` import `react-is` occurred

```
Uncaught SyntaxError: The requested module '/node_modules/react-is/index.js?v=fba0bf76' does not provide an export named 'isFragment' (at ref.js?v=fba0bf76:5:10)
```
![image](https://github.com/react-component/util/assets/19564821/58401e2d-6bfa-455c-99a7-ac1f1f21d685)

![image](https://github.com/react-component/util/assets/19564821/11cf5bee-bc2a-4a84-a459-62835622215b)

**Comment by conero** [comment]
It's work when change config file `vite.config.ts` like:

```javascript
export default defineConfig({
  optimizeDeps: {
    include: ['shallowequal', 'react-is'],
  }
}

```

**Comment by Zexoius** [comment]
occurred the same issue, but the solution does't work for me, i will reply this until solve this question.
