### ISSUE TITLE
Missing peer dependency with npm3 install

### ISSUE THREAD

**Issue by gbk** [react-component/util#5]
rc-util v3.2.0

https://github.com/react-component/util/commit/1a719d12de5ba6386ce05811f68150532f88e906

![image](https://cloud.githubusercontent.com/assets/865717/16175519/2b39df02-3623-11e6-97d6-fe0fac2724f7.png)

`react-addons-pure-render-mixin` peer-depends `react@^15.1.0`.

When I install `rc-menu`, a `UNMET PEER DEPENDENCY` error occured.

![image](https://cloud.githubusercontent.com/assets/865717/16175545/b3a7c57e-3624-11e6-8748-8f8718df1332.png)

So, would you please remove `react-addons-pure-render-mixin` or add `react` into dependencies?

**Comment by pcwinters** [comment]
👍 broke the same way via rc-calendar

**Comment by eternalsky** [comment]
react-addons-pure-render-mixin 15.x dependence 的意思是 rc 要放弃对 IE8 的兼容了吗~ peer 的 react 15.x 会和兼容 0.14.x 的组件产生依赖冲突了吧~

**Comment by benjycui** [comment]
May be we should publish `rc-util@4.0.0` which had removed `react-addons-pure-render-mixin`.
