### ISSUE TITLE
4.9.0 版本引发报错，获取不到 addEventListener

### ISSUE THREAD

**Issue by kreja** [react-component/util#52]
我的项目依赖一个三方包，这个包依赖了 rc-util，里面是这样用的：

```
const addEventListener = require('rc-util/lib/Dom/addEventListener');
...
addEventListener(window, 'resize', this.resize);
```

rc-util 4.9.0 版本做了什么？4.88 还能正常运行，4.9.0 版本就报错 `Uncaught (in promise) TypeError: addEventListener is not a function`

我没法改这个三方包，还请看看 rc-util 4.9.0 是否改出问题了。

**Comment by vagusX** [comment]
这个 issue 楼主遇到的问题主要是依赖的依赖中有 rc-util，可通过 webpack.resolve.alias 解决，需要锁定到 rc-util 4.8.8 版本

```js
alias: {
    'rc-util/lib/Dom/addEventListener': path.resolve('./node_modules/rc-util/lib/Dom/addEventListener'),
  },
```

**Comment by vagusX** [comment]
Recently, we upgraded bundle scripts to umi/father, the version of babel we used was babel 7. According to breaking changes in babel7, [add-module-exports](https://babeljs.io/docs/en/v7-migration-api#export-changes) was moved. So you must `rc-util` like this

```js
const addEventListener = require('rc-util/lib/Dom/addEventListener').default;
```

BTW, you can still use `rc-util@4.8.8` as before.
