### ISSUE TITLE
findDOMNode deprecated in react strict mode

### ISSUE THREAD

**Issue by florianwiech** [react-component/util#98]
Could we change this here somehow? (by not using findDOMNode)

[Warning about deprecated findDOMNode usage](https://reactjs.org/docs/strict-mode.html#warning-about-deprecated-finddomnode-usage)

### Usage
https://github.com/react-component/util/blob/b1c0f9f5bbff56aea2705620b11ca9c36959f9db/src/Dom/findDOMNode.ts#L12

**Comment by gugegev5** [comment]
same issue

**Comment by gugegev5** [comment]
[same issue](https://github.com/ant-design/ant-design/projects/7#card-36931870)

**Comment by soundslikeodd** [comment]
I am commenting here to see if it can raise this issue to someones attention.

**Comment by dandananddada** [comment]
same req, pls

**Comment by fnoopv** [comment]
@zombieJ 请问有修复计划吗

**Comment by RnMss** [comment]
[Same issue on version 5.34.0. ](https://github.com/react-component/util/blob/e909e6f76ea72ed3b40fb2483f93dd6bd8c6c89b/src/Dom/findDOMNode.ts#L21C12-L21C57)

**Comment by twinkle77** [comment]
same issue

**Comment by FreeDrifter** [comment]
修复了吗 ?

**Comment by noahge** [comment]
还有解决的计划吗？或者有用户自己手动解决的方法吗？

**Comment by imsunhao** [comment]
插眼，观察🔎

**Comment by Bangxw** [comment]
2024-01-10

**Comment by halo-sifon** [comment]
same issue

**Comment by zunsthy** [comment]
React 19 removed `ReactDOM.findDOMNode()` method, please fix it !

**Comment by shiyzhang** [comment]
2024-06-20
![image](https://github.com/react-component/util/assets/87290481/0651b40d-e71d-4e9d-b30b-67f22cd77212)

**Comment by Jackwew** [comment]
我使用protable后也是有这样的错误
"react": "^18.2.0",
"@ant-design/pro-components": "^2.7.10",

可以通过替换其他的版本避免这个错误吗？

**Comment by zhouzyc** [comment]
插个眼

**Comment by zhuman90** [comment]
观望

**Comment by zombieJ** [comment]
`rc-util` will return DOM directly if ref provide the dom. Or fallback to use `findDOMNode` instead. If you meet this warning, pls fire issue in the usage part instead of here.

`rc-util` 当 ref 提供的是 DOM 节点时会直接返回，只有当是 React 节点才会降级为 `findDOMNode`。如果遇到了这个 warning，请到使用了该方法的地方提 issue。

ref https://github.com/react-component/util/blob/master/src/Dom/findDOMNode.ts#L32
